prueba-master/admin/urls.py
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rest-auth/', include('rest_auth.urls')),
    # descomentar si se necesita app móvil
    # path('rest-auth/registration/', include('rest_auth.registration.urls')), 
    path('profiles/', include(('apps.profiles.urls', 'profiles'), namespace="profiles")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba-master/apps/profiles/urls.py
from django.urls import path
from apps.profiles.views import *

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
	path('home/',home_view, name='home'),
    path('readAcademicSpace',read_academic_space_view, name='readAcademicSpace'),    
    path('readRepetition',read_repetition_view, name='readRepetition'),    


]

prueba-master/templates/general/footer.html
<div class="footer mt-auto py-4 text-light bg-Cprimary ">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-6">
                <b class="text-md-left text-center mt-3">Copyright © 2023 Maeztro - Derechos Reservados</b>

            </div>
            <div class="col-12 col-md-6">
                <div class="row ">
                    <div class="col-12 col-md-5 text-center px-0">
                        <a class="text-light  text-md-right mr-md-3" href="#"><b>Términos y Condiciones</b></a><b>|</b>
                    </div>
                    <div class="col-12 col-md-7 px-0 text-center">
                        <a class="text-light text-md-left" href="#"> <b>Política de Privacidad de Datos</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

prueba-master/templates/general/header.html
<nav class="navbar navbar-expand-lg bg-Csecondary " style="position: relative; z-index: 9999;">
  
  <button class="navbar-toggler border border-light" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon text-light"><i class="fa fa-bars" aria-hidden="true"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item dropdown px-2">
        <a class="nav-link text-Cprimary" href="#" id="dropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="d-flex flex-column align-items-center">
            <i class="fa fa-list-ul fa-2x mb-1"></i>
            <div class="h6">Espacios Académicos</div>
          </div>
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdown1">
          <a class="dropdown-item" href="{% url 'profiles:readAcademicSpace' %}"><i class="fa fa fa-list-alt"></i> Espacios Académicos</a>
          <a class="dropdown-item" href="{% url 'profiles:readRepetition' %}"><i class="fa fa fa-list-alt"></i> Repetición Espacios Académicos</a>
      </li> 
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link text-light" href="#" id="dropdownCerrarSesion" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <div class="d-flex flex-column align-items-center">
            <i class="fa fa-user-circle-o fa-2x mb-1"></i>
            <div class="h6">
              {{user.first_name}} {{user.last_name}}
            </div>
            <div class="h6">
              ({{user.groups.all.0.name}})
            </div>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownCerrarSesion">
          <a class="dropdown-item " href="{% url 'profiles:logout' %}">Cerrar sesión<i class=" ml-2 fa fa-sign-in text-Cprimary " aria-hidden="true"></i></a>
        </div>
      </li>
    </ul>
  </div>
</nav>


prueba-master/templates/general/home.html
{% extends 'general/master.html' %}
{% block content %}

  <div class="row min-vh-C76 mr-10 ">
    <div class="col-12">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-center ">
          <h1 class="fw-light"><b>¡Bienvenido a Backoffice!</b></h1>
        </div>
      </div>
    </div>
    </div>
{% endblock %}

prueba-master/templates/general/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Universidad</title>
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="{% static 'bootstrap4.6/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'general/general.css' %}?{{version_static}}">
</head>

<body class="full-Cimage text-dark">   
  <div class="container-fluid">
    <div class="row h-100 mt-5 align-items-center">
      <div class="col-6 col-md-4 offset-4 card pt-3 rounded  shadow">
          <div class="row  justify-content-center">
            <h3 class="text-Csecondary"><b>¡Bienvenido!</b></h3>
          </div>
          <div class="row  justify-content-center">
            Ingrese a su Cuenta
          </div>
          <hr>
        <div class="card-body ">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Usuario</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fa fa-envelope-open-o" aria-hidden="true"></i></span>
                    </div>
                    <input type="text" id="login_username" placeholder="Ingrese su Usuario" class="form-control"
                    name="username">
                  </div>
                  <div class="help-block with-errors text-danger">{{form.errors.username}}</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Contraseña</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                      </div>
                      <input type="password" id="login_password" placeholder="Ingrese su Contraseña" class="form-control"
                        name="password">
                      <div class="input-group-prepend">
                        <span class="text-Csecondary input-group-text bg-white border-left-0">
                          <i class="fa js-eye-show fa-eye-slash"></i>
                        </span>
                      </div>
                    </div>
                    <div class="help-block with-errors text-danger">{{form.errors.password}}</div>
                </div>
              </div>
            </div>
            <div class="row mt-3 mb-3">
              <div class="col-md-12">
                <button type="submit" class="btn bg-Csecondary  btn-lg btn-block"><a class="text-Cprimary" >Ingresar</a>
                  
                </button>
              </div>
            </div>
            {% for err in form.non_field_errors %}
            <div class='row mx-0 alert-danger'>
              {{err}}
            </div>
            {% endfor %}
          </form>        
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS -->
  <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap4.6/js/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'general/general.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'general/config.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'general/apis.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'apps/profiles/generalProfile.js' %}?{{version_static}}"></script>
</body>

</html>

prueba-master/templates/general/master.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Universidad</title>
        <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static 'bootstrap4.6/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}"> 
        <link rel="stylesheet" href="{% static 'general/general.css' %}?{{version_static}}"> 
    </head>
    <body>

        <body class="d-flex flex-column min-vh-100 ">
            <!-- <body class="d-flex flex-column min-vh-100 "> -->
            <!-- <body>   -->
            <header class="mx-0">
                {% include "general/header.html" %}
                <hr class="mb-0">
            </header>
            <div class="container-fluid ">
                {% block content %}
                {% endblock %}
            </div>
            
            <!-- Modal: General -->
            <div class="modal fade {% block form_modal_margin %}{% endblock %}" id="GeneralModal">
                <div class="modal-dialog modal-dialog-scrollable modal- modal-dialog-centered ">
                    <div class="modal-content {% block form_modal_size %} {% endblock %} ">
                        <div class="modal-header">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-12">
                                        <h3 class="modal-title text-Csecondary text-center mt-2 mb-0">
                                            {% block form_modal_title %}
                                            {% endblock %}
                                        </h3>
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-12">
                                            <h6 class="modal-title">
                                                {%block form_modal_content %}
                                                {%endblock%}
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        <div class="modal-footer">
                            {% block form_modal_footter %}        
                            {% endblock %}
                            
                        </div>
                    </div>
                </div>
            </div>
           
            <!-- <footer class="mt-auto">
                {% include "general/footer.html" %}
            </footer> -->
        

        <!-- Bootstrap JS -->
        <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery/jquery.autocomplete.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap4.6/js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'general/general.js' %}?{{version_static}}"></script>
        <script type="text/javascript" src="{% static 'general/config.js' %}?{{version_static}}"></script>
        <script type="text/javascript" src="{% static 'general/apis.js' %}?{{version_static}}"></script>
          
        {% block script %}
        {% endblock %}
                     
    </body>
</html>